version: '3'
services:
  node-app:
    build:
      context: ./backend 
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
    - ./backend:/usr/src/app
    container_name: node-app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongo

volumes:
  mongo-data:
